# Site settings
title: "爆发小宇宙I"
email: 249316429@qq.com
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://htmljsp.github.io/" # the base hostname & protocol for your site
github_username: htmljsp

timezone: Beijing
plugins:
  - jekyll-feed
  - jekyll-paginate

# Build settings
highlighter: rouge
permalink: /:categories/:title/

markdown: kramdown
# markdown: redcarpet
redcarpet:
  extensions: ['fenced_code_blocks', 'tables']

paginate: 25

github: [metadata]
